### PR TITLE
Rename index.md to README.md

### PR DESCRIPTION
**Pull request by hullalex-tek**
This will cause the github page to auto display the code of conduct page

### CODE REVIEW

**Comment by zkoppert** [comment]
Doesn't the github page already display the file contents? https://tektronix.github.io/Code-Of-Conduct/

**Comment by hullalex-tek** [comment]
I didn't realize we were using GitHub pages, I was referring to when you navigate to https://github.com/tektronix/Code-Of-Conduct. 
Do you happen to know if GitHub pages will use the file if you rename it to README.md instead of index.md?

**Comment by zkoppert** [comment]
> I didn't realize we were using GitHub pages, I was referring to when you navigate to https://github.com/tektronix/Code-Of-Conduct.
> Do you happen to know if GitHub pages will use the file if you rename it to README.md instead of index.md?

Good question. Let me check.

**Comment by zkoppert** [comment]
@nlynchjo thoughts?

**Comment by nlynchjo** [comment]
yeah if the io page still renders with README instead, that's a very good rationale to change! spoilers: we do have some plans to refactor the site soon however

**Pull request merged**
